//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBook
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string BookName { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string InventoryNum { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public string GUID { get; set; }
        public string CategoryName { get; set; }
        public string MakerName { get; set; }
    }
}
